{{- if and (eq .Values.auth.mode "basic") (not .Values.auth.basic.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubesnooze-splash.fullname" . }}-basic-auth
  labels:
    {{- include "kubesnooze-splash.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.auth.basic.username | quote }}
  password: {{ .Values.auth.basic.password | quote }}
{{- end }}
