{{- if and (eq .Values.auth.mode "oidc") (not .Values.auth.oidc.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubesnooze-splash.fullname" . }}-oidc
  labels:
    {{- include "kubesnooze-splash.labels" . | nindent 4 }}
type: Opaque
stringData:
  client-id: {{ .Values.auth.oidc.clientId | quote }}
  client-secret: {{ .Values.auth.oidc.clientSecret | quote }}
  cookie-secret: {{ .Values.auth.oidc.cookieSecret | quote }}
{{- end }}
