{{- if eq .Values.auth.mode "oidc" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubesnooze-splash.fullname" . }}-oauth2-proxy
  labels:
    {{- include "kubesnooze-splash.labels" . | nindent 4 }}
    app.kubernetes.io/component: oauth2-proxy
spec:
  type: ClusterIP
  selector:
    {{- include "kubesnooze-splash.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: oauth2-proxy
  ports:
    - name: http
      port: 80
      targetPort: 4180
{{- end }}
