apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubesnooze-controller
  namespace: kubesnooze-system
  labels:
    app.kubernetes.io/name: kubesnooze
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kubesnooze
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubesnooze
    spec:
      serviceAccountName: kubesnooze-controller
      containers:
        - name: manager
          image: ghcr.io/kubesnooze/kubesnooze-controller:latest
          args:
            - "--leader-elect"
          ports:
            - containerPort: 9443
              name: webhook
            - containerPort: 8080
              name: metrics
            - containerPort: 8081
              name: health
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
